riscv/opensbi

Makefile
docs/platform/qemu_virt.md
firmware/fw_base.S
include/sbi/sbi_unpriv.h
lib/sbi_ecall.c
lib/sbi_emulate_csr.c
platform/common/sys/clint.c
platform/qemu/virt/config.mk
platform/template/config.mk

The QEMU virt machine supports both 32-bit and 64-bit RISC-V machines. This patch series adds support for the 32-bit machines.

Add 32-bit QEMU Virt support

---

docs/platform/sifive_fu540.md

Usage non-breaking hyphen breaks make docs as doxygen doesn't know
how to handle this.
This fixes make doc failure issue.
Signed-off-by: Atish Patra <atish.patra@wdc.com>

docs: Use normal hyphen instead of non-breaking hyphen

---

Makefile

On Makefile merge_objs calls ld without providing any hints on the target so on a multilib toolchain for example it will always pick the default one (elf64-littleriscv) which will then result a failure when compiling on RV32 since the objects will be 32bits and the target will be 64bits. The same happens on compile_ld that calls gcc without CFLAGS so it doesn't get mabi/march.
With this patch OpenSBI compiles on RV32 (PLATFORM_RISCV_XLEN=32), I tested fw_jump.elf on qemu (but it doesn't boot the kernel yet -bbl also doesn't boot the kernel so it may be something else).
Note that currently the newlib toolchain from riscv-gnu-toolchain doesn't support rv32imafdc (only rv32imafc) so since OpenSBI requires the d extension, it will not find the proper libgcc.a and default to the 64bit one, …

Makefile: Fix compilation on RV32

---

docs/platform/sifive_fu540.md
firmware/fw_payload.S
platform/sifive/fu540/HiFiveUnleashed-MicroSemi-Expansion.dts
platform/sifive/fu540/platform.c

This adds support for the Microsemi expansion board. There seems to be a bug with how the DTB is copied that requires the third commit to work around.

Add support for specifying device tree for the Microsemi Expansion board

---

Makefile
platform/qemu/sifive_u/config.mk
platform/qemu/virt/config.mk
platform/template/config.mk

Makes for easy and quick build-run one-stop command.
For now only added for qemu targets. It can be added for
any platform having simulator/emulator (such as QEMU).
Signed-off-by: Olof Johansson <olof@lixom.net>
Signed-off-by: Anup Patel <anup.patel@wdc.com>

Add 'make run' command for platform specific run

---

Makefile

Previously OPENSBI_CC_XLEN was not being correctly assigned either 32 or
64. It also was not assigned before config.mk was parsed. Ensure that it
will always be assigned.
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

Makefile: Fix the assignment of OPENSBI_CC_XLEN

---

Makefile

We get following error evaluating OPENSBI_CC_XLEN on
Ubuntu-18.04:
/bin/sh: 1: Bad substitution
This PR fixes above error by using "awk"

Fix error evaluating OPENSBI_CC_XLEN on Ubuntu

---

platform/template/platform.c

There was a space instead of '_' in the function `platform_final_init`.

template: Fix typo in platform_final_init

---

Makefile

Ensure the platform variable PLATFORM_RISCV_XLEN is set before we parse
the platform files.
This fixes the 32-bit openSBI FW_JUMP_ADDR.
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

Makefile: Set the platform variables before parsing the platforms

---

firmware/fw_base.S

Writable code section can cause some security problems, so move _boot_hart_done
to the data section
Signed-off-by: Xiang Wang <wxjstz@126.com>

firmware: Move _boot_hart_done to the data section & Add a barrier instruction for wait for boot hart

---

include/sbi/sbi_platform.h
lib/sbi_console.c
lib/sbi_hart.c
lib/sbi_init.c
lib/sbi_ipi.c
lib/sbi_timer.c
platform/kendryte/k210/platform.c
platform/qemu/sifive_u/platform.c
platform/qemu/virt/platform.c
platform/sifive/fu540/platform.c
platform/template/platform.c

platform should be a read-only variable, if it is placed in the data
segment, it may be exploited.
Signed-off-by: Xiang Wang \<wxjstz@126.com\>

platform: Make the `platform` read-only

---

firmware/fw_base.S

This PR contains the 2nd part of warm reset fix. It also includes the changes in previous PR (#83 ).

Warm reset fix

---

firmware/fw_base.S
include/sbi/sbi_scratch.h
lib/sbi_ipi.c

Create a sbi_ipi_data structure that holds unpacked IPI information. At
the same time remove ipi_type from the sbi_scratch struct and use a
fixed offset to access it.
This structure fits in behind the sbi_scratch structure.
This fixes https://github.com/riscv/opensbi/issues/81
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

lib: Create a sbi_ipi_data structure

---

firmware/fw_base.S

Scratch space setup needs to be done once for reboot for each
hart. _start_warm may be called several times if hart hotplug
is implemented.
Move scratch space setup to the beginning so that it is done
only once.
Fixes #42 
Signed-off-by: Atish Patra <atish.patra@wdc.com>

firmware: Move scratch setup to _start instead of _start_warm

---

platform/common/irqchip/plic.c

- platform: plic: Fix plic_set_priority()
- platform: plic: Bypass interrupt ID 0's priority programming

platform: plic fixes

---

lib/sbi_ecall.c

OpenSBI should show error trace only if any valid SBI function
does not perform as expected.
However, OpenSBI should show notify the caller with a negative
error if given SBI function ID is not valid.
Signed-off-by: Atish Patra <atish.patra@wdc.com>

lib: Return ENOTSUPP incase of invalid SBI function ID

---

platform/common/irqchip/plic.c

The codes that currently program the interrupt enable register for
S-mode disagrees with what the comments say. Fix the comments.
While we are here, add one line comment to describe what is done
for M-mode too.

platform: plic: Fix comments of programming the interrupt enable register

---

docs/firmware/fw.md
firmware/fw_base.S
firmware/objects.mk
include/sbi/sbi_scratch.h
lib/sbi_init.c

Introduce "options" in "struct sbi_scratch" and firmware can update it based on optional compile time flags before calling sbi_init().
For example, we can use it to conditionally disable the boot prints.

firmware: Introduce "options" in "struct sbi_scratch"

---

firmware/fw_base.S

When I tried to start opensbi with coreboot, I found that aligning to a 16-byte
boundary would make a copy error.
The current riscv platform does not have a 128-bit machine, and there is no need
to align the 16-byte boundary. Corrected to align to an 8-byte boundary.
Signed-off-by: Xiang Wang \<wxjstz@126.com\>

firmware: Fix source fdt alignment

---

lib/sbi_trap.c

In case we didn't handle a trap with one of the available
handlers, check if the trap comes from S or U mode and
redirect it to S mode's trap handler.
Signed-off-by: Nick Kossifidis <mick@ics.forth.gr>

lib: Redirect unhandled traps from non-M modes to S mode

---

docs/platform/ariane-fpga.md
docs/platform/platform.md
include/sbi_utils/irqchip/plic.h
lib/utils/irqchip/plic.c
platform/ariane-fpga/config.mk
platform/ariane-fpga/objects.mk
platform/ariane-fpga/platform.c

This patch adds support for Ariane platform.
We needed to enable PLIC interrupts early(like on BBL) due to some issue of the design.
Otherwise, Linux would not get any external interrupts.
Signed-off-by: Panagiotis Peristerakis <perister@ics.forth.gr>

Add support for Ariane FPGA SoC

---

firmware/fw_base.S

If core-0 have finished _fdt_reloc_done but any of other cores has not
yet left the loop in _wait_relocate_copy_done, they could never leave
the loop because _boot_status is not equal to 1.

firmware: Fix the loop condition of _wait_relocate_copy_done section
